
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CITY_CL CITY_OL COUNTRY_CL COUNTRY_OL DATE_TEXT DURATION_CL DURATION_OL EVENT_CL EVENT_DATE_CL EVENT_DATE_OL EVENT_OL GENERIC_TEXT IMAGES_CL IMAGES_OL IMAGES_TEXT LINK_CL LINK_OL LINK_TEXT POSTED_CL POSTED_OL SHAPES_LIST_CL SHAPES_LIST_OL SHAPE_CL SHAPE_OL STATES_LIST_CL STATES_LIST_OL STATE_CL STATE_OL SUMMARY_CL SUMMARY_OL TIME_CL TIME_OLufo_xml     : states_list shape_list event_liststates_list : STATES_LIST_OL state STATES_LIST_CLstate       : STATE_OL GENERIC_TEXT STATE_CL\n                    | state stateshape_list  : SHAPES_LIST_OL shape SHAPES_LIST_CLshape    : SHAPE_OL GENERIC_TEXT SHAPE_CL\n                 | shape shapeevent_list  : event_list event_individual \n\t\t          | event_individualevent_individual : EVENT_OL  link event_date time city  state country shape  duration summary posted images EVENT_CLlink   : LINK_OL LINK_TEXT LINK_CLevent_date  : EVENT_DATE_OL DATE_TEXT EVENT_DATE_CLtime   : TIME_OL GENERIC_TEXT TIME_CL city   : CITY_OL GENERIC_TEXT CITY_CL\n               | CITY_OL CITY_CLcountry   : COUNTRY_OL GENERIC_TEXT COUNTRY_CLduration   : DURATION_OL GENERIC_TEXT DURATION_CLsummary   : SUMMARY_OL GENERIC_TEXT SUMMARY_CLposted   : POSTED_OL DATE_TEXT POSTED_CLimages   : IMAGES_OL IMAGES_TEXT IMAGES_CL'
    
_lr_action_items = {'STATES_LIST_OL':([0,],[3,]),'$end':([1,8,9,16,58,],[0,-1,-9,-8,-10,]),'SHAPES_LIST_OL':([2,14,],[5,-2,]),'STATE_OL':([3,6,13,22,31,35,37,41,],[7,7,7,-3,7,7,-15,-14,]),'EVENT_OL':([4,8,9,16,20,58,],[10,10,-9,-8,-5,-10,]),'SHAPE_OL':([5,11,19,26,39,42,46,],[12,12,12,-6,12,12,-16,]),'STATES_LIST_CL':([6,13,22,],[14,-4,-3,]),'GENERIC_TEXT':([7,12,28,32,40,45,48,],[15,21,33,36,43,49,52,]),'LINK_OL':([10,],[18,]),'SHAPES_LIST_CL':([11,19,26,],[20,-7,-6,]),'COUNTRY_OL':([13,22,35,],[-4,-3,40,]),'STATE_CL':([15,],[22,]),'EVENT_DATE_OL':([17,30,],[24,-11,]),'LINK_TEXT':([18,],[25,]),'DURATION_OL':([19,26,42,],[-7,-6,45,]),'SHAPE_CL':([21,],[26,]),'TIME_OL':([23,34,],[28,-12,]),'DATE_TEXT':([24,51,],[29,56,]),'LINK_CL':([25,],[30,]),'CITY_OL':([27,38,],[32,-13,]),'EVENT_DATE_CL':([29,],[34,]),'CITY_CL':([32,36,],[37,41,]),'TIME_CL':([33,],[38,]),'COUNTRY_CL':([43,],[46,]),'SUMMARY_OL':([44,53,],[48,-17,]),'POSTED_OL':([47,57,],[51,-18,]),'DURATION_CL':([49,],[53,]),'IMAGES_OL':([50,60,],[55,-19,]),'SUMMARY_CL':([52,],[57,]),'EVENT_CL':([54,61,],[58,-20,]),'IMAGES_TEXT':([55,],[59,]),'POSTED_CL':([56,],[60,]),'IMAGES_CL':([59,],[61,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ufo_xml':([0,],[1,]),'states_list':([0,],[2,]),'shape_list':([2,],[4,]),'state':([3,6,13,31,35,],[6,13,13,35,13,]),'event_list':([4,],[8,]),'event_individual':([4,8,],[9,16,]),'shape':([5,11,19,39,42,],[11,19,19,42,19,]),'link':([10,],[17,]),'event_date':([17,],[23,]),'time':([23,],[27,]),'city':([27,],[31,]),'country':([35,],[39,]),'duration':([42,],[44,]),'summary':([44,],[47,]),'posted':([47,],[50,]),'images':([50,],[54,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ufo_xml","S'",1,None,None,None),
  ('ufo_xml -> states_list shape_list event_list','ufo_xml',3,'p_ufo_xml','ufolex.py',135),
  ('states_list -> STATES_LIST_OL state STATES_LIST_CL','states_list',3,'p_states_list','ufolex.py',138),
  ('state -> STATE_OL GENERIC_TEXT STATE_CL','state',3,'p_state','ufolex.py',141),
  ('state -> state state','state',2,'p_state','ufolex.py',142),
  ('shape_list -> SHAPES_LIST_OL shape SHAPES_LIST_CL','shape_list',3,'p_shape_list','ufolex.py',149),
  ('shape -> SHAPE_OL GENERIC_TEXT SHAPE_CL','shape',3,'p_shape','ufolex.py',152),
  ('shape -> shape shape','shape',2,'p_shape','ufolex.py',153),
  ('event_list -> event_list event_individual','event_list',2,'p_event_list','ufolex.py',160),
  ('event_list -> event_individual','event_list',1,'p_event_list','ufolex.py',161),
  ('event_individual -> EVENT_OL link event_date time city state country shape duration summary posted images EVENT_CL','event_individual',13,'p_event_individual','ufolex.py',165),
  ('link -> LINK_OL LINK_TEXT LINK_CL','link',3,'p_link','ufolex.py',168),
  ('event_date -> EVENT_DATE_OL DATE_TEXT EVENT_DATE_CL','event_date',3,'p_event_date','ufolex.py',174),
  ('time -> TIME_OL GENERIC_TEXT TIME_CL','time',3,'p_time','ufolex.py',180),
  ('city -> CITY_OL GENERIC_TEXT CITY_CL','city',3,'p_city','ufolex.py',187),
  ('city -> CITY_OL CITY_CL','city',2,'p_city','ufolex.py',188),
  ('country -> COUNTRY_OL GENERIC_TEXT COUNTRY_CL','country',3,'p_country','ufolex.py',197),
  ('duration -> DURATION_OL GENERIC_TEXT DURATION_CL','duration',3,'p_duration','ufolex.py',203),
  ('summary -> SUMMARY_OL GENERIC_TEXT SUMMARY_CL','summary',3,'p_summary','ufolex.py',209),
  ('posted -> POSTED_OL DATE_TEXT POSTED_CL','posted',3,'p_posted','ufolex.py',215),
  ('images -> IMAGES_OL IMAGES_TEXT IMAGES_CL','images',3,'p_images','ufolex.py',221),
]
